---
abstract: 'Easily and safely change directory'
author:
  - 'Ahmad Syaltut <Isyaltut@gmail.com>'
build_requires:
  File::Path: 0
  File::Spec::Functions: 0
  File::Temp: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-cd
requires:
  Carp: 0
  Cwd: 0
  Exporter: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/Syaltut/File-cd
  repository: ssh://git@github.com:Syaltut/File-cd.git
version: 0.001
